# Generated by Django 3.1.1 on 2020-11-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guser',
            options={'verbose_name_plural': 'GSM사용자'},
        ),
    ]
