# Generated by Django 3.1.1 on 2020-11-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmUser', '0002_auto_20201104_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='useremail',
            field=models.EmailField(default='test@gsm.hs.kr', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
